export const ATTRIBUTE_TYPES = {
  OBJECT: 'object',
  ARRAY: 'array',
  STRING: 'string',
};

export const MAPPINGS = {
  ID: ATTRIBUTE_TYPES.STRING,
  TYPE: ATTRIBUTE_TYPES.STRING,
  PARAMS: ATTRIBUTE_TYPES.OBJECT,
  NEXT: ATTRIBUTE_TYPES.ARRAY,
  FIELDS: ATTRIBUTE_TYPES.OBJECT,
};
